### PR TITLE
fix(import) Fix the `&'static` hack for imported functions

### PR DESCRIPTION
**Pull request by Hywan**
Closes #185.
Follow up of #140. 

Good job @kngwyu and @davidhewitt!

### CODE REVIEW

**Comment by davidhewitt** [comment]
Nice! FWIW there's a deadlock in pyO3 `0.10.0` which I think will be resolved soon with a patch release, see https://github.com/PyO3/pyo3/pull/924

Also if I can comment on your solution implemented here, `Python` is currently a zero sized type and implements `Copy` so you should probably pass it not as a reference. Also did you try to compile without lifetime annotations? I have a feeling you should not need them here.

**Comment by davidhewitt** [comment]
Lol I guess that might have been the deadlock xD

**Comment by Hywan** [comment]
I don't think it is related to the deadlock, but only Bors being Bors sometimes ;-) (kidding, this tool is awesome).

You're right, the lifetime can now be inferred properly by the borrow checker!

**Pull request merged**
